apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: enterprise-contract
spec:
  generators:
    - clusters:
        values:
          sourceRoot: components/enterprise-contract
          environment: staging
          clusterDir: ""
  template:
    metadata:
      name: enterprise-contract-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}'
        repoURL: https://github.com/avi-biton/infra-deployments-community.git
        targetRevision: main
      destination:
        server: '{{server}}'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 15s
