apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  generators:
    - clusters:
        values:
          # sourceRoot: components/external-secrets
          environment: staging
          clusterDir: ""
  template:
    metadata:
      name: external-secrets-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.environment}}'
        repoURL: https://charts.external-secrets.io
        targetRevision: v0.10.5
        chart: external-secrets
      destination:
        server: '{{server}}'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 15s
